version: '3.2'

services:
    portainer:
        image: portainer/portainer
        container_name: "${COMPOSE_PROJECT_NAME}_portainer"
        command: -H unix:///var/run/docker.sock
        ports:
            - 9000:9000
            - 8000:8000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        restart: unless-stopped

volumes:
  portainer_data: